"""PDF export service for generating formatted PDF reports."""
import os
from datetime import datetime, date as date_type
from typing import List, Optional
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.platypus.flowables import HRFlowable

from models.export import ExportConfig
from services.csv_manager import csv_manager
from services.calculator import calculator
from services.debt_service import debt_service
from services.portfolio_service import portfolio_service
from utils.dates import now_iso, get_current_month


class PDFExportService:
    """Service for generating PDF exports."""
    
    def __init__(self):
        """Initialize PDF export service."""
        self.exports_dir = "exports"
        self._ensure_exports_dir()
    
    def _ensure_exports_dir(self):
        """Ensure exports directory exists."""
        if not os.path.exists(self.exports_dir):
            os.makedirs(self.exports_dir)
    
    def _get_page_size(self, config: ExportConfig):
        """Get page size from config."""
        return letter if config.page_size == "Letter" else A4
    
    def _create_header(self, config: ExportConfig, title: str, subtitle: Optional[str] = None) -> List:
        """Create PDF header."""
        styles = getSampleStyleSheet()
        elements = []
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=18,
            textColor=colors.HexColor('#1f2937'),
            spaceAfter=6,
            alignment=1  # Center
        )
        elements.append(Paragraph(title, title_style))
        
        # Subtitle
        if subtitle:
            subtitle_style = ParagraphStyle(
                'CustomSubtitle',
                parent=styles['Normal'],
                fontSize=12,
                textColor=colors.HexColor('#6b7280'),
                spaceAfter=12,
                alignment=1  # Center
            )
            elements.append(Paragraph(subtitle, subtitle_style))
        
        # Company name
        company_style = ParagraphStyle(
            'Company',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#9ca3af'),
            spaceAfter=12,
            alignment=1  # Center
        )
        elements.append(Paragraph(config.company_name, company_style))
        
        # Horizontal line
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e5e7eb')))
        elements.append(Spacer(1, 12))
        
        return elements
    
    def _create_footer_text(self, config: ExportConfig) -> str:
        """Create footer text."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return f"Generated by {config.company_name} on {timestamp}"
    
    def _format_currency(self, amount: float, config: ExportConfig) -> str:
        """Format currency value."""
        formatted = f"{amount:{config.number_format}}"
        return f"{config.base_currency} {formatted}"
    
    def export_transactions_pdf(
        self,
        start_date: Optional[date_type],
        end_date: Optional[date_type],
        account_id: Optional[str],
        category_id: Optional[str],
        transaction_type: Optional[str],
        config: ExportConfig
    ) -> str:
        """
        Export transactions to PDF.
        
        Returns:
            File path of generated PDF
        """
        # Load data
        transactions = csv_manager.read_csv("transactions.csv")
        accounts = csv_manager.read_csv("accounts.csv")
        categories = csv_manager.read_csv("categories.csv")
        
        # Create account and category lookup
        account_map = {acc['id']: acc['name'] for acc in accounts}
        category_map = {cat['id']: cat['name'] for cat in categories}
        
        # Filter transactions
        filtered = []
        for txn in transactions:
            # Date filter
            if start_date and txn.get('date', '') < str(start_date):
                continue
            if end_date and txn.get('date', '') > str(end_date):
                continue
            
            # Account filter
            if account_id and txn.get('account_id') != account_id:
                continue
            
            # Category filter
            if category_id and txn.get('category_id') != category_id:
                continue
            
            # Type filter
            if transaction_type and txn.get('type') != transaction_type:
                continue
            
            filtered.append(txn)
        
        # Sort by date descending
        filtered.sort(key=lambda x: x.get('date', ''), reverse=True)
        
        # Generate filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"transactions_{timestamp}.pdf"
        filepath = os.path.join(self.exports_dir, filename)
        
        # Create PDF
        doc = SimpleDocTemplate(
            filepath,
            pagesize=self._get_page_size(config),
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )
        
        elements = []
        
        # Header
        date_range = ""
        if start_date and end_date:
            date_range = f"{start_date} to {end_date}"
        elif start_date:
            date_range = f"From {start_date}"
        elif end_date:
            date_range = f"Until {end_date}"
        
        subtitle = f"Transaction Report - {date_range}" if date_range else "Transaction Report"
        elements.extend(self._create_header(config, "Transactions", subtitle))
        
        # Summary
        total_income = sum(float(t.get('amount', 0)) for t in filtered if t.get('type') == 'income')
        total_expenses = sum(abs(float(t.get('amount', 0))) for t in filtered if t.get('type') == 'expense')
        net = total_income - total_expenses
        
        summary_data = [
            ['Total Income:', self._format_currency(total_income, config)],
            ['Total Expenses:', self._format_currency(total_expenses, config)],
            ['Net:', self._format_currency(net, config)]
        ]
        
        summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
        summary_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(summary_table)
        elements.append(Spacer(1, 20))
        
        # Transactions table
        if filtered:
            table_data = [['Date', 'Description', 'Category', 'Account', 'Amount']]
            
            for txn in filtered:
                amount = float(txn.get('amount', 0))
                amount_str = self._format_currency(abs(amount), config)
                if txn.get('type') == 'expense':
                    amount_str = f"({amount_str})"
                
                table_data.append([
                    txn.get('date', ''),
                    txn.get('description', '')[:30],
                    category_map.get(txn.get('category_id', ''), 'Unknown')[:20],
                    account_map.get(txn.get('account_id', ''), 'Unknown')[:20],
                    amount_str
                ])
            
            transactions_table = Table(table_data, colWidths=[1*inch, 2*inch, 1.5*inch, 1.5*inch, 1.5*inch])
            transactions_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1f2937')),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (-1, 0), (-1, -1), 'RIGHT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('TOPPADDING', (0, 1), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 4),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')])
            ]))
            elements.append(transactions_table)
        else:
            styles = getSampleStyleSheet()
            elements.append(Paragraph("No transactions found for the selected criteria.", styles['Normal']))
        
        # Build PDF
        doc.build(elements)
        
        return filepath
    
    def export_financial_summary_pdf(self, config: ExportConfig) -> str:
        """
        Export financial summary to PDF.
        
        Returns:
            File path of generated PDF
        """
        # Load data
        accounts = csv_manager.read_csv("accounts.csv")
        transactions = csv_manager.read_csv("transactions.csv")
        categories = csv_manager.read_csv("categories.csv")
        debts = csv_manager.read_csv("debts.csv")
        goals = csv_manager.read_csv("goals.csv")
        settings_data = csv_manager.read_json("settings.json")
        
        base_currency = settings_data.get('base_currency', config.base_currency)
        current_month = get_current_month()
        
        # Calculate metrics
        total_balance = calculator.calculate_total_balance(accounts, transactions, base_currency)
        monthly = calculator.calculate_monthly_totals(current_month, transactions, base_currency)
        savings_rate = calculator.calculate_savings_rate(monthly['income'], monthly['expenses'])
        net_worth = calculator.calculate_net_worth(total_balance, debts)
        total_debt = debt_service.get_total_debt()
        
        # Portfolio value
        try:
            portfolio_value = portfolio_service.get_total_portfolio_value(base_currency)
            total_net_worth = net_worth + portfolio_value
        except Exception:
            portfolio_value = 0.0
            total_net_worth = net_worth
        
        # Generate filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"financial_summary_{timestamp}.pdf"
        filepath = os.path.join(self.exports_dir, filename)
        
        # Create PDF
        doc = SimpleDocTemplate(
            filepath,
            pagesize=self._get_page_size(config),
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )
        
        elements = []
        
        # Header
        elements.extend(self._create_header(config, "Financial Summary", f"As of {datetime.now().strftime('%Y-%m-%d')}"))
        
        # Overview section
        styles = getSampleStyleSheet()
        heading_style = ParagraphStyle(
            'SectionHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1f2937'),
            spaceAfter=12,
            spaceBefore=12
        )
        
        elements.append(Paragraph("Overview", heading_style))
        
        overview_data = [
            ['Total Balance:', self._format_currency(total_balance, config)],
            ['Total Net Worth:', self._format_currency(total_net_worth, config)],
            ['Total Debt:', self._format_currency(total_debt, config)],
            ['Portfolio Value:', self._format_currency(portfolio_value, config)]
        ]
        
        overview_table = Table(overview_data, colWidths=[3*inch, 2.5*inch])
        overview_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(overview_table)
        elements.append(Spacer(1, 20))
        
        # Monthly summary
        elements.append(Paragraph(f"Monthly Summary ({current_month})", heading_style))
        
        monthly_data = [
            ['Monthly Income:', self._format_currency(monthly['income'], config)],
            ['Monthly Expenses:', self._format_currency(monthly['expenses'], config)],
            ['Monthly Surplus:', self._format_currency(monthly['net'], config)],
            ['Savings Rate:', f"{savings_rate:.1f}%"]
        ]
        
        monthly_table = Table(monthly_data, colWidths=[3*inch, 2.5*inch])
        monthly_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(monthly_table)
        elements.append(Spacer(1, 20))
        
        # Goals progress
        if goals:
            elements.append(Paragraph("Goals Progress", heading_style))
            
            goals_data = [['Goal', 'Target', 'Current', 'Progress']]
            for goal in goals[:5]:  # Top 5 goals
                target = float(goal.get('target_amount', 0))
                current = float(goal.get('current_amount', 0))
                progress = (current / target * 100) if target > 0 else 0
                
                goals_data.append([
                    goal.get('name', '')[:30],
                    self._format_currency(target, config),
                    self._format_currency(current, config),
                    f"{progress:.1f}%"
                ])
            
            goals_table = Table(goals_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1*inch])
            goals_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1f2937')),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('TOPPADDING', (0, 1), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 4),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb'))
            ]))
            elements.append(goals_table)
        
        # Build PDF
        doc.build(elements)
        
        return filepath


    def export_investment_portfolio_pdf(
        self,
        include_transactions: bool,
        investment_type: Optional[str],
        config: ExportConfig
    ) -> str:
        """
        Export investment portfolio to PDF.

        Returns:
            File path of generated PDF
        """
        from services.investment_service import investment_service

        # Load investments
        investments = investment_service.list_investments(type_filter=investment_type)

        # Get portfolio summary
        portfolio_summary = portfolio_service.get_portfolio_summary(config.base_currency)

        # Generate filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"investment_portfolio_{timestamp}.pdf"
        filepath = os.path.join(self.exports_dir, filename)

        # Create PDF
        doc = SimpleDocTemplate(
            filepath,
            pagesize=self._get_page_size(config),
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )

        elements = []

        # Header
        subtitle = f"Investment Type: {investment_type}" if investment_type else "All Investments"
        elements.extend(self._create_header(config, "Investment Portfolio", subtitle))

        # Portfolio summary
        styles = getSampleStyleSheet()
        heading_style = ParagraphStyle(
            'SectionHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1f2937'),
            spaceAfter=12,
            spaceBefore=12
        )

        elements.append(Paragraph("Portfolio Summary", heading_style))

        summary_data = [
            ['Total Investments:', str(portfolio_summary.total_investments)],
            ['Total Value:', self._format_currency(portfolio_summary.total_value, config)],
            ['Total Cost:', self._format_currency(portfolio_summary.total_cost, config)],
            ['Profit/Loss:', self._format_currency(portfolio_summary.total_profit_loss, config)],
            ['Return:', f"{portfolio_summary.total_profit_loss_percentage:.2f}%"]
        ]

        summary_table = Table(summary_data, colWidths=[3*inch, 2.5*inch])
        summary_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(summary_table)
        elements.append(Spacer(1, 20))

        # Investments table
        if investments:
            elements.append(Paragraph("Holdings", heading_style))

            table_data = [['Symbol', 'Name', 'Type', 'Quantity', 'Avg Cost', 'Current', 'Value', 'P/L %']]

            for inv in investments:
                perf = investment_service.get_investment_performance(inv.id)

                table_data.append([
                    inv.symbol,
                    inv.name[:20],
                    inv.type,
                    f"{perf.quantity:.4f}",
                    f"{perf.average_cost:.2f}",
                    f"{perf.current_price:.2f}",
                    self._format_currency(perf.current_value, config),
                    f"{perf.profit_loss_percentage:.2f}%"
                ])

            investments_table = Table(table_data, colWidths=[0.8*inch, 1.5*inch, 0.7*inch, 0.8*inch, 0.8*inch, 0.8*inch, 1.2*inch, 0.8*inch])
            investments_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1f2937')),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (3, 0), (-1, -1), 'RIGHT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('TOPPADDING', (0, 1), (-1, -1), 3),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 3),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')])
            ]))
            elements.append(investments_table)

        # Build PDF
        doc.build(elements)

        return filepath

    def export_debt_report_pdf(
        self,
        include_paid_off: bool,
        config: ExportConfig
    ) -> str:
        """
        Export debt report to PDF.

        Returns:
            File path of generated PDF
        """
        # Load debts
        debts = csv_manager.read_csv("debts.csv")

        # Filter debts
        if not include_paid_off:
            debts = [d for d in debts if float(d.get('current_balance', 0)) > 0]

        # Calculate totals
        total_debt = sum(float(d.get('current_balance', 0)) for d in debts)
        total_minimum = sum(float(d.get('minimum_payment', 0)) for d in debts)

        # Generate filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"debt_report_{timestamp}.pdf"
        filepath = os.path.join(self.exports_dir, filename)

        # Create PDF
        doc = SimpleDocTemplate(
            filepath,
            pagesize=self._get_page_size(config),
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=0.75*inch,
            bottomMargin=0.75*inch
        )

        elements = []

        # Header
        elements.extend(self._create_header(config, "Debt Report", f"As of {datetime.now().strftime('%Y-%m-%d')}"))

        # Summary
        styles = getSampleStyleSheet()
        heading_style = ParagraphStyle(
            'SectionHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1f2937'),
            spaceAfter=12,
            spaceBefore=12
        )

        elements.append(Paragraph("Summary", heading_style))

        summary_data = [
            ['Total Debt:', self._format_currency(total_debt, config)],
            ['Total Minimum Payment:', self._format_currency(total_minimum, config)],
            ['Number of Debts:', str(len(debts))]
        ]

        summary_table = Table(summary_data, colWidths=[3*inch, 2.5*inch])
        summary_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 11),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        elements.append(summary_table)
        elements.append(Spacer(1, 20))

        # Debts table
        if debts:
            elements.append(Paragraph("Debt Details", heading_style))

            table_data = [['Name', 'Type', 'Balance', 'Interest Rate', 'Min Payment', 'Due Date']]

            for debt in debts:
                table_data.append([
                    debt.get('name', '')[:25],
                    debt.get('type', ''),
                    self._format_currency(float(debt.get('current_balance', 0)), config),
                    f"{float(debt.get('interest_rate', 0)):.2f}%",
                    self._format_currency(float(debt.get('minimum_payment', 0)), config),
                    debt.get('due_date', '')
                ])

            debts_table = Table(table_data, colWidths=[1.8*inch, 1*inch, 1.3*inch, 1*inch, 1.2*inch, 1*inch])
            debts_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1f2937')),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (2, 0), (-1, -1), 'RIGHT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 9),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('TOPPADDING', (0, 1), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 4),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f9fafb')])
            ]))
            elements.append(debts_table)
        else:
            elements.append(Paragraph("No debts found.", styles['Normal']))

        # Build PDF
        doc.build(elements)

        return filepath


# Singleton instance
pdf_export_service = PDFExportService()

